[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "8.9.0"

[[redirects]]
 from = "/small/*"
 to = "/.netlify/functions/get-avatar?size=50&user=:splat"
 status = 200

[[redirects]]
 from = "/mid/*"
 to = "/.netlify/functions/get-avatar?size=200&user=:splat"
 status = 200

[[redirects]]
 from = "/large/*"
 to = "/.netlify/functions/get-avatar?size=400&user=:splat"
 status = 200


[[redirects]]
 from = "/test/*"
 to = "https://www.google.co.uk/?q=:splat"
 status = 200
