[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "8.9.0"

[[redirects]]
 from = "/api/*"
 to = "/.netlify/functions/get-avatar?user=:splat"
 status = 200


[[redirects]]
 from = "/test/*"
 to = "https://google.com/?q=:splat"
 status = 200
